### ISSUE TITLE
Chrome webdriver for mac should install 64 bit driver

### ISSUE THREAD

**Issue by jkieboom** [balumuriraj/Grunt-Selenium-Plugin#4]
Currently tries to install mac32.zip, but that doesn't seem to exist. Instead it should probably try installing mac64.zip instead.

**Comment by balumuriraj** [comment]
This is fixed now - https://github.com/balumuriraj/Grunt-Selenium-Plugin/commit/d685f44ef6834406a3e8c62a8cba00cf8d59b523.

Thanks @jkieboom :)
