### ISSUE TITLE
Upgrade `download` dependency to resolve moderate vulnerability

### ISSUE THREAD

**Issue by dasa** [balumuriraj/Grunt-Selenium-Plugin#5]
Reported by `npm audit`:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/828058/42648539-1ab8917e-85bc-11e8-8daf-ff5b79b708b5.png">

**Comment by balumuriraj** [comment]
Fixed with - https://github.com/balumuriraj/Grunt-Selenium-Plugin/commit/10afb6f2e5d1cad8695272e8405e4ecdec0fdc7a
